controller_list:
  - name: right_arm_controller
    type: effort_controllers/JointPositionController
    joints:
      - jright_shoulder
      - jright_upper_arm
      - jright_forearm
  - name: right_hand_controller
    type: effort_controllers/JointPositionController
    joints:
      - jright_grip_rhand
